name: 'Auto Issue Post Action'
description: 'Action test'
author: 'valonso'
inputs:
  secrets: 
    required: true
    description: 'all secrets...?'
    # default: 'Default value'
runs:
  using: 'node16'
  main: 'index.js'