name: "Auto Issue Post Action"
description: "Action test"
author: "valonso"
inputs:
    secrets:
        required: true
        description: "JSON secrets"
        # default: 'Default value'
runs:
    using: "node16"
    main: "dist/index.js"
